FROM mysql:5.7 as builder

RUN ["sed", "-i", "s/exec \"$@\"/echo \"not running $@\"/", "/usr/local/bin/docker-entrypoint.sh"]

ENV MYSQL_USER=exampleuser \
    MYSQL_PASSWORD=examplepass \
    MYSQL_DATABASE=exampledb \
    MYSQL_ROOT_PASSWORD=root

COPY exampledb.sql /docker-entrypoint-initdb.d/

RUN ["/usr/local/bin/docker-entrypoint.sh", "mysqld", "--datadir", "/initialized-db"]

FROM mysql:5.7

COPY --from=builder /initialized-db /var/lib/mysql