version: '3.9'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 82:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    build: 
        context: .
        dockerfile: Dockerfile.db
    ports: 
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: '0'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: